### PR TITLE
Ft/progress bar

### PR DESCRIPTION
**Pull request by cwagner22**

### CODE REVIEW

**Review by Xzirez — APPROVED** [review]

**Comment by Jennimar17** [comment]
1. **the elements that have been left unreviewed is because they are corrected in another newer PR. you can merge now and the comments should be taken into account**

image
image
image

**Comment by NataliaAvila-PM** [comment]
Thanks for the comments @Jennimar17. 

Because the comments on that table are unrelated to the main component of this PR, let's leave them for later and move forward now.

**Comment by NataliaAvila-PM** [comment]
This is also corrected in the PR https://github.com/zignaly-open/zignaly-ui/pull/63

**Comment by NataliaAvila-PM** [comment]
Hi guys @Xzirez @cwagner22 @german-schneck on chromatic everything is good. There are some stories that will be fixed with https://github.com/zignaly-open/zignaly-ui/pull/63 but if we mark the screenshots are valid, will be considered as valid, when they are not. That's the reason why appears as pending. Could you merge with having some of those tests as pending?

**Pull request merged**
