### PR TITLE
Ft/login

### PR DESCRIPTION
**Pull request by german-schneck**

### CODE REVIEW

**Comment by Xzirez** [comment]
I think i will refactor the withdrawal modal to yup as well.

**Review by Xzirez — APPROVED** [review]

**Comment by Jennimar17** [comment]
image
image

**Comment by Jennimar17** [comment]
image
image
image
image

**Comment by Jennimar17** [comment]
image

**Comment by german-schneck** [comment]
@Jennimar17  These failures in modal do not correspond to this functionality. It seems that they are brought from the develop branch. 

The ideal in these cases is to merge the branch and fix them in a new one.

**Pull request merged**
