### PR TITLE
Style/update/tabs and table

### PR DESCRIPTION
**Pull request by tastafur**
- update styles table

### CODE REVIEW

**Comment by NataliaAvila-PM** [comment]
Nice work here Ruben. I can see a lot of progress and improvement. I have noticed some small details to review:

1) Full name of the coin. According to Figma it should be 13px / weight 400
image

in the storybook appears as:
image

2) Besides that I have noticed the following when I select the sort by column:


Is this because by default is not sorted by any column? 

3) Just to mention here because I know that you are already working on it, the alignment of the columns.

4) My last comment is that I have seen that we have included some coins as listed coins EUR or USD. We can include the conversion to these coins but not as listed coins becuase they are FIAT. 

Please let me know any comments or questions.

**Comment by tastafur** [comment]
Is this because by default is not sorted by any column?  by default is sorted by any column, I have updated the column data so that it can be seen better. 
The

**Comment by NataliaAvila-PM** [comment]
Hi @tastafur everything looks correct!

The only thing that I have noticed, and we can move forward and fix it after merging, is that for some reason, the zig icon is not visible.
image

Another detail, for the coins and units we should use the text style Body Small 13px instead of h4.  
image

Could you please also check the colors? For the number, It should be Neutral100 (#c1c1c8) instead of Neutral000 and for the coin should be Neutral400 #706F82. I am not sure if they are wrong in the inspect
image

image

If you don't mind to check this quickly. Thanks in advance!

**Comment by tastafur** [comment]
For some reason we don't have the zig coin icon in cloudinary `https://res.cloudinary.com/zignaly/image/upload/c_scale,w_36,h_36,r_max/coins-binance/ZIG`

The other weird things you've seen are already resolved for the color I was not using the typography component well

**Comment by NataliaAvila-PM** [comment]
chop-approve-cop-approve

It appears as a fail because the ZIG coin logo error, but it is ready to move forward @tastafur 
We don't have it probably because it is not in Binance :)

**Pull request merged**
