### PR TITLE
feat: add toogleButton

### PR DESCRIPTION
**Pull request by Xzirez**
- Creates a basic toogleButton
- Adds color white to theme

### CODE REVIEW

**Comment by Jennimar17** [comment]
image
https://www.figma.com/file/eaFFY4dXO69tMnUDXxHYAD/Radio%2C-Checkbox%2C-Toggle?node-id=502%3A39

image


image

**Comment by Jennimar17** [comment]
**- the elements that have been left unreviewed are because they are wrong but corrected in another PR**

**Comment by Xzirez** [comment]
@NataliaAvila-PM @Jennimar17 I fixed the color on this component now, however the text is not a type we have in the typography component. Should I proceed with this new type of text and add it to the typography component or will the text in the design be changed?

**Comment by NataliaAvila-PM** [comment]
You are right @Xzirez . For the text we should go with the H5, which is 11px instead of 12px. 

@Jennimar17 please comment in Figma.

**Pull request merged**
