### PR TITLE
feat: add charts component

### PR DESCRIPTION
**Pull request by Xzirez**
Note: The large chart is not completely finished in functionality. This is a simple draft for its basic functionality.

### CODE REVIEW

**Comment by Jennimar17** [comment]
image
Some color changes are needed.
I made some changes in my local in the
code to fix the color that is requested. I hope Vetle is correct.

basically it is to change to the indicated red color and follow the percentage specifications described in figma

**Comment by Jennimar17** [comment]
As for the rest, it looks very good

**Comment by Xzirez** [comment]
@Jennimar17 Feel free to push this change yourself. I forgot to add this color. Should be an easy commit to start with :)

commit should follow conventional commits so either:

git commit —amend 

then press : q w to write using vim

git push —force

or you can do:

git commit -m “fix: add correct red color”

git push

**Comment by Jennimar17** [comment]
@Xzirez i tried but i need permission to push changes
image

**Comment by tastafur** [comment]
Captura de Pantalla 2022-05-18 a las 9 58 53
@Xzirez putting spaces in folder names can sometimes give problems between names, between Unix and windows systems, try not to put them in, I updated the ones I saw before, since

**Comment by tastafur** [comment]
Captura de Pantalla 2022-05-18 a las 10 08 33
This should be like this, because before you called a variable that was not used, it was a strange behaviour, so as I paint it now, it is rendered twice, 1 without the useEffect being launched and the next one after the positiveOrNegative is called, this number of renders would be correct, I upload it corrected

**Comment by tastafur** [comment]
@Xzirez LGTM!

**Comment by Xzirez** [comment]
Oki i will remember folder names. It's common yes. Gonna merge this one now. @tastafur @NataliaAvila-PM

**Pull request merged**
