### PR TITLE
feat(modals) add my account confirmation modal

### PR DESCRIPTION
**Pull request by Xzirez**

### CODE REVIEW

**Comment by german-schneck** [comment]
Are they 3 different modals? Or is it 1 modal with 3 different types of content?

**Comment by Xzirez** [comment]
> Are they 3 different modals? Or is it 1 modal with 3 different types of content?

There are 3 modals: 

- Withdrawal modal is the entrance to the withdrawal process

- The confirmation modal is the step after the withdrawal modal which confirms the withdrawal.

- Deposit is the entrance to the deposit process

**Comment by Jennimar17** [comment]
image

**Comment by Jennimar17** [comment]
image

**Comment by Jennimar17** [comment]
image
image
image

**Comment by Jennimar17** [comment]
image
image
image

**Comment by Jennimar17** [comment]
image

**Comment by Jennimar17** [comment]
image
image

**Pull request merged**
