### PR TITLE
feat: multiple typography stories

### PR DESCRIPTION
**Pull request by Xzirez**
- Added stories for all variations of typography

### CODE REVIEW

**Comment by german-schneck** [comment]
Fixed:
image

**Comment by NataliaAvila-PM** [comment]
Hi @Xzirez 

This is super useful first step in the multi-story to be able to check automatically using chromatic. This should save us a lot of time in the long term.

I have noticed one thing that we should review. In the headings, we are showing texts with different font weights. For Headings, we should have only the option of weight 500 but not any other to avoid confusion.  

image

And another comment, just cutting hair here, it will be super cool if instead of showing Example Text for all of them we specify something like "H1 Heading Example Text", "H2 Heading Example Text", etc. For the bodies for example "Body Demibold" or "Body Small Regular". This way it is also easier to identify them.

For some reason the stories Button and Big Number doesn't work properly on the inspect. Do they have any difference with the other two?

**Comment by Xzirez** [comment]
@NataliaAvila-PM Changes applied. Check new build when ready.

**Comment by NataliaAvila-PM** [comment]
@Xzirez everything is fixed now thanks. There is one thing that I have noticed in the controls of the components that generates a crash. Is it possible to remove that?  or is it time consuming?

**Comment by Xzirez** [comment]
@NataliaAvila-PM Fixed the crashing controls

**Pull request merged**
