### PR TITLE
feat: user dashboard

### PR DESCRIPTION
**Pull request by Xzirez**

### CODE REVIEW

**Comment by NataliaAvila-PM** [comment]
A couple of quick comments.

1. Please review the edit icon size2. 
image

2. Now when you click on a column, the size changes of the header cell changes. This was working before without changing the size. So I believe at some point we have broken it. 



3. Please add some rows to cover all the possible combinations.

Please @Jennimar17 review in detail. 

RESOLVED!

**Comment by Jennimar17** [comment]
image

image

RESOLVED!!!

**Comment by Jennimar17** [comment]
image
https://www.figma.com/file/NOO2RAkuZGR2BSbfpkeuKk/User-Dashboard?node-id=10%3A3903

RESOLVED!!!!

**Comment by Jennimar17** [comment]
image

https://www.figma.com/file/SfGI4q5RrXQe2BhNmg56cb/Service-Dashboard?node-id=451%3A12945


- here the size is perfect, but it is not centered

RESOLVED

**Comment by Jennimar17** [comment]
image

**Comment by Jennimar17** [comment]
> A couple of quick comments.
> 
> 1. Please review the edit icon size2.
>    image
> 2. Now when you click on a column, the size changes of the header cell changes. This was working before without changing the size. So I believe at some point we have broken it.
> 
>  [ ](https://user-images.githubusercontent.com/69221733/169382367-f63d70be-227a-47a2-9975-f501e474ebda.gif)  [ ](https://user-images.githubusercontent.com/69221733/169382367-f63d70be-227a-47a2-9975-f501e474ebda.gif)
> 
> 3. Please add some rows to cover all the possible combinations.
> 
> Please @Jennimar17 review in detail.

**Comment by NataliaAvila-PM** [comment]
I believe there was an error closing the PR. I have reopened it.

**Comment by tastafur** [comment]
@Xzirez there are things that have been broken from the other tables, both as was centred the percentage and the sorting symbol that previously went on the right side, the sorting symbol on the right side also has some styles so that it does not give a jump when it appears, check it so that it does the same behaviour depending on its arrangement that if it does not give a jump the text when the sorting symbol appears
Captura de Pantalla 2022-05-23 a las 8 48 09

**Comment by Xzirez** [comment]
@tastafur this is an old build I believe. In my local, it looks good. Check this link https://624edb7402c737003aedd62f-khhapkdcpv.chromatic.com/?path=/story/display-table--investors

**Comment by tastafur** [comment]
Upload the changes otherwise you can't test it xD on remote it looks like I have shown you
Captura de Pantalla 2022-05-23 a las 9 08 25

**Comment by Xzirez** [comment]
@tastafur It's fixed and pushed. 

Screenshot 2022-05-23 at 09 15 42

**Comment by tastafur** [comment]
Captura de Pantalla 2022-05-23 a las 10 10 14

now i get the changes, what was going wrong, the order symbol is not aligning with respect to the texts, can you look at it? and another thing can you put another row where the chart appears with the percentage symbol as shown by @Jennimar17 ?

**Comment by Xzirez** [comment]
@tastafur Yes the icon has to be centered. It's a tricky fix. 

No I cannot put another row. The chart first has to be smaller. Right now I am "tricking" the library by having a large container around it. It's not possible to place the text close enough to the chart due to this.

**Comment by tastafur** [comment]
You did not find a @german-schneck solution for this on Friday?

**Pull request merged**
