### PR TITLE
Fix/table/sort

### PR DESCRIPTION
**Pull request by tastafur**
- Fix tables sorts

### CODE REVIEW

**Comment by cwagner22** [comment]
@tastafur Thanks for looking at an implementation of the sort feature. However, I have some doubts regarding using sortByPointDecimal everywhere (that would also need to be exported for the webapp). This seems like a hack to overcome the fact that we are not rendering data the correct way. Indeed we should use `Cell` when wanting to render custom markup as [here](https://stackoverflow.com/a/63223734/1494428). If we do that then the sorting issue we had before will be fixed.
Also sortType should be memoized [it seems](https://react-table.tanstack.com/docs/api/useSortBy).

**Comment by NataliaAvila-PM** [comment]
Comments also here: https://github.com/zignaly-open/zignaly-ui/pull/63

**Comment by tastafur** [comment]
Hi @cwagner22 ,
It is not because of what you say that it fails, it is because NumberFormat formats the values to represent them visually, putting it in a cell function does not matter if it is going to be formatted anyway, it does not have to do, then you have to use a function to sort. As you say it is necessary to memorize it but in storybook it does not like in the hitoria to use the hooks for that reason in the example it is not memorized, but if there is a comment that says it that it is necessary to meomorize it, that it leaves it, put. I'm going to create another PR and close this only with the sorting because the table has continued to be touched and this has been left far behind and gives conflicts.

**Comment by cwagner22** [comment]
@tastafur Right, but instead of passing jsx with `PriceLabel` or `NumberFormat` components, we could pass the data, and then in the columns `Cell`, format it. Like I did here: https://codesandbox.io/s/falling-platform-th63ml?file=/src/App.js
In the Age column, I modified it to use an object so we could use anything, like passing a coin name and value.

**Pull request closed without merging**
