### PR TITLE
Ft/icon button with drop down

### PR DESCRIPTION
**Pull request by german-schneck**
### Description
The dropdown container is fully customizable, ie. The content is displayed without margins so that from the outside you can manage its content.

### Props:

**IconButtonProps.**
```
export type IconButtonProps = {
  variant?: IconButtonVariants;
  icon: string;
  size: IconButtonSizes;
  disabled?: boolean;
  dropDownOptions: {
    width?: string;
    alignment?: String;
  };
  onClick: React.MouseEventHandler<HTMLButtonElement> | null;
  renderDropDown: ReactElement<any> | null;
};
```

**IconButtonSizes.**
```
export enum IconButtonSizes {
  SMALL = "small",
  NORMAL = "normal",
  LARGE = "large",
  XLARGE = "xlarge",
}
```

**IconButtonVariants.**
```
export enum IconButtonVariants {
  PRIMARY = "primary",
  SECONDARY = "secondary",
  FLAT = "flat",
}
```

**DropdownAlignment.**
```
export enum DropdownAlignment {
  LEFT = "left",
  RIGHT = "right",
}
```
### Simple Component (PRIMARY)
image

### Simple Component (Secondary)
image

### Simple Component (Flat)
image

### With DropDown
image

### CODE REVIEW

**Comment by german-schneck** [comment]
@NataliaAvila-PM 

I don't know if we have a defined style on the button dropdown, I have based on a screenshot that I have seen in figma.
I would need to know the final colors and shadows.

image

**Review by cwagner22 — APPROVED** [review]

**Comment by cwagner22** [comment]
LGTM, please check the types errors

**Comment by german-schneck** [comment]
@NataliaAvila-PM, @tastafur, @Xzirez, @cwagner22 this is done.

**Comment by NataliaAvila-PM** [comment]
HI @german-schneck

I have reviewed the component. Please if you can check the conflicts to merge in develop. I have reviewed the component in any case and these are the things that I have found

Secondary border color. it should be Neutral600 #35334A
image

image

Could you please double-check the background color of the dropdown?? It should be #12152c Dropdown background, please.

image

Thank you German!

**Comment by german-schneck** [comment]
Thank you @NataliaAvila-PM of your feedback. I will check it and solve the merge issue.

**Comment by german-schneck** [comment]
@NataliaAvila-PM 

The Dropdown background is:

image
image

Please confirm if everything is correct. I have fixed the border, also I have solved the conflicts and solved some problems with the checkbox (apparently it was rendering wrong with the new tables).

**Comment by NataliaAvila-PM** [comment]
@german-schneck Here you have an example of dropdown:
image

https://www.figma.com/file/ROYL3Amojd4Q0y2M0NntVt/My-Account?node-id=379%3A18478

background  #12152c is correct.

**Comment by NataliaAvila-PM** [comment]
@german-schneck I have reviewed the components that you have updated. The only issue is in the table of the coin for some reason buttons have disappeared.

**Comment by german-schneck** [comment]
Fixed @NataliaAvila-PM 

image

**Comment by NataliaAvila-PM** [comment]
There is a problem when I try to review this PR in Chromatic and it is that it is still linked to build 110. In this build, we run out of screenshots and we fix it later. @Xzirez could you please take a look? TIA

**Comment by Xzirez** [comment]
Let's see if it builds new build now.

**Comment by NataliaAvila-PM** [comment]
@german-schneck Please review because some components don't look updated with the last version in develop.

**Comment by german-schneck** [comment]
@NataliaAvila-PM updated now!
Thanks.

**Comment by NataliaAvila-PM** [comment]
Perfect now! thanks!

**Pull request merged**
